# Generated by Django 4.2.7 on 2025-12-05 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='universities/logos/')),
                ('iframe_3d_tour_url', models.URLField(blank=True, max_length=500)),
                ('tuition', models.DecimalField(decimal_places=2, help_text='Annual tuition fee', max_digits=12)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('study_form', models.CharField(choices=[('full-time', 'Full-time'), ('part-time', 'Part-time'), ('both', 'Full-time & Part-time')], default='full-time', max_length=20)),
                ('has_dormitory', models.BooleanField(default=False)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True)),
                ('students_count', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('programs', models.ManyToManyField(blank=True, related_name='universities', to='universities.program')),
            ],
            options={
                'verbose_name_plural': 'Universities',
                'ordering': ['-rating', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UniversityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='universities/gallery/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='universities.university')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
